import type { ContentJSON } from '@/lib/getContentFromSupabase'

export const demoContent: ContentJSON = {
  en: {
    meta: {
      title: 'Sample Developer — Portfolio',
      description: 'A sample portfolio for a full-stack developer.',
      lang: 'en',
      dir: 'ltr',
    },
    nav: {
      logo: 'Sample Developer',
      links: [
        { label: 'Home', href: '#hero' },
        { label: 'About', href: '#about' },
        { label: 'Skills', href: '#skills' },
        { label: 'Projects', href: '#projects' },
        { label: 'Career', href: '#career' },
        { label: 'Contact', href: '#contact' },
      ],
    },
    hero: {
      greeting: 'Hello, I am',
      name: 'Sample Developer',
      bio: 'I build useful, accessible web experiences with modern technologies.',
      cta_primary: 'Explore projects',
      cta_primary_href: '#projects',
      cta_secondary: 'View CV',
      cta_secondary_href: '/cv',
      roles: ['Full-Stack Developer', 'Frontend Developer', 'Problem Solver'],
      scroll_hint: 'Scroll to explore',
    },
    about: {
      section_label: 'About',
      heading: 'Building thoughtful digital experiences',
      paragraphs: [
        'This is sample content for previewing the portfolio locally.',
        'Replace it with your own background, interests, and experience.',
      ],
      stats: [
        { label: 'Years Experience', value: 'X+' },
        { label: 'Projects', value: 'X+' },
        { label: 'Happy Clients', value: 'X+' },
      ],
    },
    skills: {
      section_label: 'Skills',
      heading: 'Tools I work with',
      items: [
        { name: 'React / Next.js', icon: 'SiReact', category: 'frontend', color: '#61dafb', is_primary: true },
        { name: 'TypeScript', icon: 'SiTypescript', category: 'frontend', color: '#3178c6', is_primary: true },
        { name: 'Tailwind CSS', icon: 'SiTailwindcss', category: 'frontend', color: '#38bdf8', is_primary: true },
        { name: 'Node.js', icon: 'SiNodedotjs', category: 'backend', color: '#6cc24a' },
        { name: 'PostgreSQL', icon: 'SiPostgresql', category: 'db', color: '#336791' },
        { name: 'Supabase', icon: 'SiSupabase', category: 'db', color: '#3ecf8e' },
      ],
    },
    projects: {
      section_label: 'Projects',
      heading: 'Selected work',
      items: [
        {
          title: 'Sample Storefront',
          description: 'A responsive online storefront built with modern web technologies.',
          image: '/images/project-placeholder.svg',
          tags: ['Next.js', 'TypeScript', 'Supabase'],
          category: 'Full-Stack',
          featured: true,
          primaryLink: { url: 'https://example.com/projects/storefront' },
          secondaryLink: { url: 'https://example.com/projects/storefront' },
        },
        {
          title: 'Sample Workspace',
          description: 'A collaborative workspace concept with a clean, accessible interface.',
          image: '/images/project-placeholder.svg',
          tags: ['React', 'Node.js'],
          category: 'Web App',
          featured: true,
          primaryLink: { url: 'https://example.com/projects/workspace' },
          secondaryLink: { url: 'https://example.com/projects/workspace' },
        },
        {
          title: 'Sample Dashboard',
          description: 'A dashboard concept for exploring data and tracking useful metrics.',
          image: '/images/project-placeholder.svg',
          tags: ['TypeScript', 'Charts'],
          category: 'Dashboard',
          featured: true,
          primaryLink: { url: 'https://example.com/projects/dashboard' },
          secondaryLink: { url: 'https://example.com/projects/dashboard' },
        },
      ],
    },
    career: {
      section_label: 'Experience',
      heading: 'A sample career path',
      items: [
        {
          role: 'Full-Stack Developer',
          company: 'Example Company',
          startDate: '20XX',
          endDate: 'Present',
          description: 'Sample experience entry. Replace it with your own work history.',
        },
      ],
    },
    social: {
      section_label: 'Get in touch',
      heading: 'Let’s build something together',
      subheading: 'Send a message or find me on these sample platforms.',
      email: 'hello@example.com',
      available_badge: true,
      availability_text: 'Available for work',
      email_copy_label: 'Copy email',
      email_copied_label: 'Copied!',
      links: [
        { platform: 'GitHub', url: 'https://github.com/your-username', color: '#fff', icon: 'SiGithub' },
        { platform: 'LinkedIn', url: 'https://linkedin.com/in/your-username', color: '#0a66c2', icon: 'SiLinkedin' },
      ],
    },
    footer: {
      copyright: '© 2026 Sample Developer. Replace this sample content.',
      back_to_top: 'Back to top',
    },
    cv: { en: '', ar: '' },
    github: { username: '' },
  },
  ar: {
    meta: {
      title: 'مطور تجريبي — الموقع الشخصي',
      description: 'نموذج لمعرض أعمال مطور ويب.',
      lang: 'ar',
      dir: 'rtl',
    },
    nav: {
      logo: 'مطور تجريبي',
      links: [
        { label: 'الرئيسية', href: '#hero' },
        { label: 'عني', href: '#about' },
        { label: 'المهارات', href: '#skills' },
        { label: 'المشاريع', href: '#projects' },
        { label: 'الخبرات', href: '#career' },
        { label: 'تواصل معي', href: '#contact' },
      ],
    },
    hero: {
      greeting: 'مرحباً، أنا',
      name: 'مطور تجريبي',
      bio: 'أبني تجارب ويب مفيدة وسهلة الاستخدام باستخدام تقنيات حديثة.',
      cta_primary: 'استكشف المشاريع',
      cta_primary_href: '#projects',
      cta_secondary: 'السيرة الذاتية',
      cta_secondary_href: '/cv',
      roles: ['مطور Full-Stack', 'مطور واجهات', 'حلّال للمشكلات'],
      scroll_hint: 'مرر للاستكشاف',
    },
    about: {
      section_label: 'نبذة',
      heading: 'بناء تجارب رقمية مميزة',
      paragraphs: [
        'هذا محتوى تجريبي لمعاينة الموقع محلياً.',
        'استبدله بخلفيتك واهتماماتك وخبراتك.',
      ],
      stats: [
        { label: 'سنوات الخبرة', value: '+X' },
        { label: 'المشاريع', value: '+X' },
        { label: 'العملاء', value: '+X' },
      ],
    },
    skills: {
      section_label: 'المهارات',
      heading: 'أدوات أستخدمها',
      items: [
        { name: 'React / Next.js', icon: 'SiReact', category: 'frontend', color: '#61dafb', is_primary: true },
        { name: 'TypeScript', icon: 'SiTypescript', category: 'frontend', color: '#3178c6', is_primary: true },
        { name: 'Tailwind CSS', icon: 'SiTailwindcss', category: 'frontend', color: '#38bdf8', is_primary: true },
        { name: 'Node.js', icon: 'SiNodedotjs', category: 'backend', color: '#6cc24a' },
        { name: 'PostgreSQL', icon: 'SiPostgresql', category: 'db', color: '#336791' },
        { name: 'Supabase', icon: 'SiSupabase', category: 'db', color: '#3ecf8e' },
      ],
    },
    projects: {
      section_label: 'المشاريع',
      heading: 'أعمال مختارة',
      items: [
        {
          title: 'متجر تجريبي',
          description: 'متجر إلكتروني متجاوب مبني باستخدام تقنيات ويب حديثة.',
          image: '/images/project-placeholder.svg',
          tags: ['Next.js', 'TypeScript', 'Supabase'],
          category: 'Full-Stack',
          featured: true,
          primaryLink: { url: 'https://example.com/projects/storefront' },
          secondaryLink: { url: 'https://example.com/projects/storefront' },
        },
        {
          title: 'مساحة عمل تجريبية',
          description: 'نموذج لمساحة عمل تعاونية بواجهة بسيطة وسهلة الاستخدام.',
          image: '/images/project-placeholder.svg',
          tags: ['React', 'Node.js'],
          category: 'Web App',
          featured: true,
          primaryLink: { url: 'https://example.com/projects/workspace' },
          secondaryLink: { url: 'https://example.com/projects/workspace' },
        },
        {
          title: 'لوحة تحكم تجريبية',
          description: 'نموذج لوحة تحكم لاستكشاف البيانات ومتابعة المؤشرات.',
          image: '/images/project-placeholder.svg',
          tags: ['TypeScript', 'Charts'],
          category: 'Dashboard',
          featured: true,
          primaryLink: { url: 'https://example.com/projects/dashboard' },
          secondaryLink: { url: 'https://example.com/projects/dashboard' },
        },
      ],
    },
    career: {
      section_label: 'الخبرة',
      heading: 'مسار مهني تجريبي',
      items: [
        {
          role: 'مطور Full-Stack',
          company: 'شركة نموذجية',
          startDate: '20XX',
          endDate: 'الحاضر',
          description: 'خبرة عملية نموذجية. استبدلها بخبراتك المهنية.',
        },
      ],
    },
    social: {
      section_label: 'تواصل معي',
      heading: 'لنبنِ شيئاً مميزاً معاً',
      subheading: 'أرسل رسالة أو تواصل عبر المنصات التجريبية.',
      email: 'hello@example.com',
      available_badge: true,
      availability_text: 'متاح للعمل',
      email_copy_label: 'نسخ البريد',
      email_copied_label: 'تم النسخ!',
      links: [
        { platform: 'GitHub', url: 'https://github.com/your-username', color: '#fff', icon: 'SiGithub' },
        { platform: 'LinkedIn', url: 'https://linkedin.com/in/your-username', color: '#0a66c2', icon: 'SiLinkedin' },
      ],
    },
    footer: {
      copyright: '© 2026 مطور تجريبي. استبدل هذا المحتوى.',
      back_to_top: 'العودة للأعلى',
    },
    cv: { en: '', ar: '' },
    github: { username: '' },
  },
}
